#!/bin/sh
set -eu

PLACEHOLDER_SIZE="${GAMESTICK_USERDATA_PLACEHOLDER_SIZE:-64M}"

if [ ! -f "$BINARIES_DIR/genimage.cfg" ]; then
	echo "ERROR: $BINARIES_DIR/genimage.cfg was not generated by post-build.sh" >&2
	exit 1
fi

truncate -s "$PLACEHOLDER_SIZE" "$BINARIES_DIR/userdata-partition.bin"

support/scripts/genimage.sh -c "$BINARIES_DIR/genimage.cfg"

if [ -f "$BINARIES_DIR/sdcard.img" ]; then
	cp -f "$BINARIES_DIR/sdcard.img" "$BASE_DIR/sdcard.img"
fi
